<div class="navbar"><a name="top" id="top"></a>
	<a href="/education/" title="Learning Curve Home" class="navlink">Learning Curve Home</a>
	&nbsp;|&nbsp;
	<a href="/education/" title="Index of Topics" class="navlink">Index of Topics</a>
	&nbsp;|&nbsp;
	<a href="/education/focuson/" title="Focus on" class="navlink">Focus on</a>
	&nbsp;|&nbsp;
	<a href="/contact/" title="Contact us" class="navlink">Contact&nbsp;us</a>
</div>