<div class="footer">
		 <a href="/contact/" class="footertext">Contact us</a> 
			| <a href="/education/focuson/domesday/credits/" class="footertext">Credits</a> 
			| <a class="footertext" href="/help/"
			onclick="openPopupWindow('/help/','lcpop','620','500','scrollbars=yes,resizable=yes','yes');return document.MM_returnValue">Help</a> 
			| <a class="footertext" href="/education/focuson/domesday/glossary/" onclick="PRO_openPopupWindow('/education/focuson/domesday/glossary/','lcpop','620','500','scrollbars=yes,resizable=yes','yes');return document.MM_returnValue">Glossary</a> 
			|  <a href="/education/focuson/domesday/teachers/" class="footertext">Teacher's notes</a>
	</div>
