<meta name="DC.rights" content="http://www.nationalarchives.gov.uk/legal/copyright.htm" />

<meta name="DC.publisher" content="The National Archives, Kew, Surrey TW9 4DU" />

<meta name="DC.creator" content="The National Archives" />

<meta name="DC.language" scheme="ISO 639-2/T" content="eng" />

<meta name="DC.format" scheme="DCTERMS.IMT" content="text/html" />

<meta name="DC.date.created" scheme="DCTERMS.W3CDTF" content="2006-05-01" />

<meta name="DC.date.modified" scheme="DCTERMS.W3CDTF" content="2006-05-01" />
	
<meta name="DC.coverage.temporal" content="1000-1241" /> 
	
<meta name="eGMS.subject.category" scheme="GCL" content="Libraries and archives" />
	
<meta name="eGMS.subject.keyword" content="Domesday Book, William I, Normans, Battle of Hastings, Conqueror, KS2, KS3, Little Domesday, Great Domesday, Edward Confesssor, survey, original documents, key stage 3, keystage 2, Learning Curve, Snapshots" />
	
<meta name="keywords" content="Domesday Book, William I, Normans, Battle of Hastings, Conqueror, KS2, KS3, Little Domesday, Great Domesday, Edward Confesssor, survey, original documents, key stage 3, keystage 2, Learning Curve, Snapshots" />

<meta name="DC.description" content="Domesday Book: What can we learn about England in the 11th century; this classroom lesson examines the Domesday Book, using documents from The National Archives." />
	
<meta name="description" content="Domesday Book: What can we learn about England in the 11th century; this classroom lesson examines the Domesday Book, using documents from The National Archives." />
