<div class="topBanner">
	<div class="logo">
	<a href="http://www.nationalarchives.gov.uk"><img src="/images/micrositea.gif" width="44" height="30" alt="The National Archives" align="middle" /></a>
	<a href="/education/"><img src="/education/focuson/domesday/images/sm_learningcurvelogo.gif" alt="Learning Curve" width="121" height="31" border="0" title="Learning Curve" align="middle"/></a>
	</div>
	<div class="functionBut">
		<span id="popBut1"></span>
	</div>
</div>